### ISSUE TITLE
Explain the "Nice" part

### ISSUE THREAD

**Issue by dandv** [stratogee/relative-time#2]
In particular, does the time update itself automatically as time passes by (as @copleykj's [livestamp](https://atmospherejs.com/copleykj/livestamp) does)?

**Comment by unboundmusic** [comment]
It just uses a different algorithm to convert the distance to text. For example it would say "Wednesday at 6:05pm" if the distance ago is less than a week, whereas timeago would always say the actual date. Likewise, if the date was yesterday it says "yesterday at...", etc.
